name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install uv
      run: |
        pip install uv
        
    - name: Install dependencies
      run: |
        uv venv
        . .venv/bin/activate
        uv pip install -e .
        uv pip install pytest pytest-cov pytest-asyncio pytest-mock
        
    - name: Set up environment variables
      run: |
        # Create a .env file with mock values for testing
        echo "OPENAI_API_KEY=sk-test" > .env
        echo "DENO_PATH=/usr/bin/node" >> .env
        
    - name: Run tests
      run: |
        . .venv/bin/activate
        pytest --cov=. --cov-report=xml
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false